image: etna/drone-php-nginx
env:
  - APPLICATION_ENV=drone
  - DOWNLOAD_URL=http://localhost:10000/
  - DOWNLOAD_URL_KEY=toto
  - COMPOSER_PROCESS_TIMEOUT=3000
  - COVERALLS_REPO_TOKEN=$$COVERALLS_TOKEN
  - COVERALLS_SERVICE_NAME=drone.io
script:
  - composer self-update
  - composer install --dev --no-interaction --prefer-source
  - composer phing
  - composer coveralls
notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    username: drone
    channel: $$SLACK_CHANNEL
    on_started: true
    on_failure: true
    on_success: true
